module.exports = {
  'reply': ['panda','fox','cat'],
  'tweet': ['sad','happy','angry'],
  'follow':[],
  'directmsg':[],
  'hint':[],
  'hashtags':[],
  'doctor':[],
  'travel':[],
  'adventure':[],
  'origintweet':['I am #reply.a# #tweet#.'],
  'originreply':[],
  'origindm':[],
  'originfollow':[],
}