module.exports = {
  'reply': ['I like Hashtags. They are #sound#. Just like the #places# of #travel#',
  				'#ideas# in the #places# makes you #winhint# sometimes',
				'remember to #winhint# when you think about... #quotes#',
				'#mysteries# of the universe, heard of the #losehint# at the edge of #travel#',
				'#winhint# when you think of #travel# beyond your known world, I was there recently #adventure# of the #positiveemotion# #villains#'],
  'follow':['have you heard of #mysteries# at the #losehint# of #travel#',
				'#losehint# of interesting fact: #places# of #travel# are #emotion#',
				'word on the grapevine is #places# of #travel# are #losehint#',
				'#losehint# around the corner and remember #quotes#',
				'#mysteries#, lets stop and #winhint# because of the #sound# #villains#'],
  'directmsg':['I like Hashtags. They are #sound#. Just like the #places# of #travel#',
  					'#ideas# in the #sound# #places# of #travel# makes you #winhint# sometimes',
					'remember to #winhint# when you think about... #quotes#',
					'#mysteries# of the universe, heard of the #losehint# at the edge of #travel#',
					'#winhint# when you think of #travel# beyond your known world, I was there recently #adventure# of the #positiveemotion# #villains#',
					'sometimes I only listen to hashtags'],
  'tweet': ['#sound# and #emotion# thats what the #places# are like in #travel#',
  				'#ideas#... kinda funny isnt it. Much like #ideas# of the #travel# people. Same yet different.',
				'#mysteries#... #quotes# ',
				'#quotes#... Makes you #emotion# doesnt it',
				'#travel# has many mysteries to its name like #mysteries# beyond #ideas#',
				'#villains# sometimes make me #negativeemotion#',
				'#adventure#... gotta do what you gotta do even if youre up against #villains#'],
  'mysteries':['weeping angels',
  					'that one thing on that one diamond planet',
					'time',
					'space being super big and not empty enough',
					'timey wimey spacey wacey',
					'destruction of information',
					'being right every once in awhile'],
	'villains':['daleks',
					'shadows',
					'cybermen',
					'weeping angels',
					'me'],
  'quotes':['capitalism in space',
				'dont blink',
				'run!',
				'just smile',
				'life can be a cunning enemy',
				'fined for dying',
				'fairyland looks completely different',
				'those dinosaurs on that space ship',
				'space is a very silent place',
				'yes, yes I do speak baby',
				'five minutes is an eternity',
				'I do most of my best work ordering others around'],
  'adventure':['saving the planet',
  					'solving mysteries'],
  'places':['skies',
  				'mountains',
				'rivers',
				'seas',
				'lakes',
				'forests',
				'planes'],
  'travel':['Raxacoricofallapatorius',
  				'Mondas',
				'Florana',
				'Earth',
				'Narrah',
				'Tharos',
				'Ty',
				'Zoth',
				'Mogar',
				'Kladdavor',
				'Luminos',
				'Argos',
				'Benelisa'],
  'emotion':['#negativeemotion#','#positiveemotion#'],
  'negativeemotion':['angry',
							'sad',
							'kinda hurt',
							'slightly annoyed',
							'a tinsy bit vexed'],
  'positiveemotion':['happy',
							'overjoyed',
							'elated',
							'jubilant'],
  'sound':['silent',
			  'loud',
			  'faint',
			  'deafening',
			  'whispering'],
  'ideas':['belief',
			  'dream',
			  'fate',
			  'freedom',
			  'knowledge'],
  'winhint':['SMILE', 'WONDER*','YELL', 'TURN', '*WRITE'],
  'losehint':['NOSE', 'TEXAS', 'DINER'],
  'hashtags':['DoctorWho', 'TARDIS', 'NASAHubble', 'Gallifrey','nasahqphoto'],
  'doctor':['the doctor', 'the TARDIS'],
  'origintweet':['#tweet#.'],
  'originreply':['Twitter is weird isnt it, #reply#.',
  					  'You know what is crazy #mysteries#, not more crazy than #reply#.',
					  '#reply#, thats it.',
					  'wondering over things to wonder, #reply#.'],
  'origindm':['#directmsg#'],
  'originfollow':['huh, #follow#', 'hi, #follow#', 'yo, #follow#', 'hello, #follow#', 'sigh, #follow#', 'why you? #follow#'],
  'originalreadywon':['ummm, arent you #positiveemotion#. You win. I aint talking to you anymore.',
  							 'You have already won, dont you have anything better to do?',
							 'your words, they sound #positiveemotion#. You already won, I think you should move on now',
							 'are you #positiveemotion#. You won. hmm I feel #negativeemotion#'],
  'originalreadylost':['You can still win. Keep your eyes forward.',
							  'You lost yeah, but trust in your #ideas# you can still win',
							  '#sound# words from you, #ideas# is your way. You can win if you try.',
							  '#emotion#, what do you feel?'],
  'originhastags':['#hashtags#']
}